version: '3.8'

services:
  vocechat-server:
    build:
      context: .
      dockerfile: Dockerfile.full
    container_name: vocechat-server
    ports:
      - "3000:3000"
    volumes:
      - ./data:/home/vocechat-server/data
    restart: unless-stopped
    environment:
      - RUST_LOG=info